### PR TITLE
CMakeLists.txt: use GNUInstallDirs for LIBEXECDIR and DATADIR

### PR DESCRIPTION
**Pull request by decathorpe**
Fixes Issue #7.

### CODE REVIEW

**Comment by davidmhewitt** [comment]
This breaks the `data/org.pantheon.agent-geoclue2.desktop.in.in` file. It uses the LIBDIR cmake variable. Otherwise, I'm not opposed to this change.

**Comment by decathorpe** [comment]
Oh, I missed that. I'll fix it.

**Comment by decathorpe** [comment]
Is this right now? I'm not that familiar with CMake.

**Comment by davidmhewitt** [comment]
Yeah, it's great. Tested and working here on the elementary side.

**Pull request merged**
